### ISSUE TITLE
Locally-scoped options pollute global options

### ISSUE THREAD

**Issue by goodguyry** [goodguyry/postcss-tidy-columns#1]
When `@tidy` options are used in a block, their values persist and must be manually overridden to restore the global options.

Given the following:
```css
@tidy columns 16;
@tidy gap 0.625rem / true;
@tidy edge 32px;
@tidy site-max 75rem;

div {
	@tidy columns 12;
	@tidy gap 1.25rem / false;
	tidy-span: 2;
}
@media (min-width: 60rem) {
	div {
		@tidy edge 1rem;
		tidy-span: 3;
		tidy-offset-left: 2;
	}
}
```

The block in the media query will inherit the `columns` and `gap` values from the previous block.

**Acceptance criteria:**
Locally-scoped options do not interfere with the global options, and do not cascade through to other rule blocks.
