### ISSUE TITLE
Scoped @tidy `edge` and `gap` rules aren't overriding when set to `0`

### ISSUE THREAD

**Issue by goodguyry** [goodguyry/postcss-tidy-columns#16]
```css
@tidy columns 12;
@tidy site-max 90rem;
@tidy gap 1.25rem;
@tidy edge 0.625rem;

.scoped-atrules--zero {
	@tidy gap 0;
	@tidy edge 0;
	tidy-span: 2;
}
```

```diff
- Expected
+ Received

.scoped-atrules--zero {
- 	width: calc((100vw / 12) * 2);
- 	max-width: calc((90rem / 12) * 2);
+ 	width: calc((((100vw - 0.625rem * 2) / 12 - 1.1458rem) * 2) + 1.25rem);
+ 	max-width: calc((((90rem - 0.625rem * 2) / 12 - 1.1458rem) * 2) + 1.25rem);
}
```
