### ISSUE TITLE
More than one `tidy-*` function on a shorthand property

### ISSUE THREAD

**Issue by goodguyry** [goodguyry/postcss-tidy-columns#22]
Only the first instance of a tidy function is replaced by the plugin.

Example:
```css
.span-function--multi {
	padding: 0 tidy-offset(2) 0 tidy-offset-full(3);
	margin: 0 calc(tidy-offset-full(2) + 50px) 0 tidy-offset(1);
}
```

Expected:

```css
.span-function--multi {
	padding: 0 calc((((100vw - 0.625rem * 2) / 12 - 1.1458rem) * 2) + 1.25rem * 2) 0 calc((((90rem - 0.625rem * 2) / 12 - 1.1458rem) * 3) + 1.25rem * 3);
	margin: 0 calc(((((90rem - 0.625rem * 2) / 12 - 1.1458rem) * 2) + 1.25rem * 2) + 50px) 0 calc(((100vw - 0.625rem * 2) / 12 - 1.1458rem) + 1.25rem);
}
```

Actual:

```css
.span-function--multi {
	padding: 0 calc((((100vw - 0.625rem * 2) / 12 - 1.1458rem) * 2) + 1.25rem * 2) 0 tidy-offset-full(3);
	margin: 0 calc(((((90rem - 0.625rem * 2) / 12 - 1.1458rem) * 2) + 1.25rem * 2) + 50px) 0 tidy-offset(1);
}
```
