### ISSUE TITLE
`stripExtraCalc` not working as expected

### ISSUE THREAD

**Issue by goodguyry** [goodguyry/postcss-tidy-columns#35]
Refs #34 

Nested `calc()` is only being stripped when it is at the beginning of the expression.

```scss
// Passing.
div { 
  margin-left: calc(tidy-offset(3) + 20px); 
}
```

```scss
// Failing.
div { 
  margin-left: calc(20px + tidy-offset(3)); 
}
```
