### ISSUE TITLE
More than one function in a declaration breaks debug mode

### ISSUE THREAD

**Issue by goodguyry** [goodguyry/postcss-tidy-columns#46]
When more than one `tidy-*` function is used in the same declaration, PostCSS throws an error with option `debug: true`.

```scss
div {
  margin: 0 tidy-var(edge) 0 tidy-var(gap);
}
```

**Expected:**
```scss
div {
  /* margin: 0 tidy-var(edge) 0 tidy-var(gap) */
  margin: 0 1.875rem 0 1.25rem;
}
```

**Actual:**
```
TypeError: Cannot read property 'insertAfter' of undefined
```
